### ISSUE TITLE
All those redundant types...

### ISSUE THREAD

**Issue by markpundsack** [jclem/detour#2]
These all seem redundant:

```
  t.string  :group_type
  t.string  :percentage_type
  t.string  :flag_subject_type
```

I know it's nice to use the polymorphic keyword, but isn't there a better way? Only one of these would exist at a time.

**Comment by jclem** [comment]
@markpundsack Yeah, doing some stuff with single-table inheritance would help to clean this up, so we could just have `RecordFlag`, `PercentageFlag`, `GroupFlag` that are all on this table, but could share a single `flaggable_type` column.

**Comment by jclem** [comment]
Closed by https://github.com/jclem/active_record_rollout/commit/b5f6d8f211b83d24c3e4de230ab253e398ca2a8c, implementing an STI model. Features can now be queried for `feature.flaggable_flags`, `feature.group_flags`, and `feature.percentage_flags`.
